= 1. ÚVODNÍ STRÁNKA

== Nadpis první úrovně

=== Nadpis druhé úrovně

==== Nadpis třetí úrovně

===== Nadpis čtvrté úrovně

Tohle je naprosto výplňový text verze *{page-component-version}*. Neslouží žádnému informativnímu účelu kromě toho, že na něm testuju AsciiDoc a Antoru.

A hlavně to, jestli Antora zvládá češtinu.

Tohle je úvodní stránka Dokumentu jedna, která je zároveň nastavená i jako homepage celého projektu. nachází se v modulu ROOT jako soubor `+index.adoc+`.

Budu zkoušet různé formátování a styly. Jsem docela zvědavý co z toho celého vypadne, protože jsem zatím testoval jenom drobnosti. Tohle je největší test, kterému tu věc chci podrobit.

Název Q&A seznamu::
[qanda]
K čemu to bude sloužit?::
K testu rozložení, zobrazení jazyka a tak.

Koupíš mi pivo?::
Ne, nekoupím.

WARNING: Takhle bude vypadat něco důležitého.

NOTE: A takhle budou vypadat věci, které zmíním jenom tak mezi řečí.

Podobných levelů poznámek je tam ale mnohem víc.

TIP: Třeba tenhle, když chcete poukázat na nějakou kůl fíčuru.

A tak, no. A teď už je čas na preview stromu dokumentů/kapitol (dodám později. teď chci hlavně rozchodit repo a tak).
